### ISSUE TITLE
Invalid configuration for installing requirements in docker container

### ISSUE THREAD

**Issue by ljungnickel** [pwnforce/uSBS#9]
Hi,
when I clone the repository and run "make run" to build the docker container, the installation fails due to the package "setuptools", which has to have a version higher than 46.4.0. To fix this issue and be able to run the docker container properly, I changed this line in the Dockerfile:

`RUN pip install pathlib2 lief==0.8.0.post7 pwntools==4.3.1 keystone-engine==0.9.2 six==1.16.0`
to 
`RUN pip install pyelftools==0.24 pathlib2 lief==0.8.0.post7 pwntools==4.3.1 keystone-engine==0.9.2 six==1.16.0`
This way I am able to build to docker container properly.

Could you change this in the Dockerfile configuration?
Thanks!

**Comment by JWH-96** [comment]
I encountered a problem while using uSBS, can I ask for your advice? 

- **When instrumenting binary file, the following error was encountered. For some elf files, uSBS can execute normally. But for elf files compiled with the following source code, errors will occur. Flashing to the development board can run normally. May I ask what caused this?**

ubuntu@ubuntu-virtual-machine:~/Desktop/New Folder/uSBS-master/usbs$ python2 asan.py /home/ubuntu/Desktop/STM32/firmware.elf
Found .text
Traceback (most recent call last):
File "asan.py", line 452, in
rewriter.rewrite(sys.argv[1], "arm")
File "/home/ubuntu/Desktop/Sanitizer/uSBS-master/usbs/usbs.py", line 91, in rewrite
mapping = mapper.gen_mapping()
File "/home/ubuntu/Desktop/Sanitizer/uSBS-master/usbs/usbs_mapper.py", line 104, in gen_mapping
newins = self.translator.translate_one(ins, None)
File "/home/ubuntu/Desktop/Sanitizer/uSBS-master/usbs/usbs_translator.py", line 148, in translate_one
return self._translate_tbb(ins, mapping)
File "/home/ubuntu/Desktop/Sanitizer/uSBS-master/usbs/usbs_translator.py", line 1154, in _translate_tbb
self.context.read_byte(tbb_offset_table_addr + i * 1)
File "/home/ubuntu/Desktop/Sanitizer/uSBS-master/usbs/context.py", line 56, in read_byte
return struct.unpack('B',value)[0]
struct.error: unpack requires a string argument of length 1

**- STM32 source code**

```
#include "Arduino.h"
#ifndef LED_BUILTIN
#define LED_BUILTIN 13
#endif

char *buf = 0;
size_t input_len = 0;
int led_state = 0;

#define FUZZ_INPUT_SIZE 2048

void setup() {
    pinMode(LED_BUILTIN, OUTPUT);
    digitalWrite(LED_BUILTIN, HIGH);
    Serial.begin(38400);
    buf = (char*)calloc(1, FUZZ_INPUT_SIZE);
    if(!buf) {
        digitalWrite(LED_BUILTIN, LOW);
        delay(1000000);
        return;
    }
}

void serial_read_bytes(char *buf, size_t length) {
    size_t bytes_read = 0;
    while (bytes_read < length) {
        if (!Serial.available()) continue;
        char byte = Serial.read();
        buf[bytes_read] = byte;
        bytes_read += 1;
    }
}

void process_data(char* buffer, unsigned int length) {
	char stack_array[20];
	if( length > 0 && buffer[0] == 'b') 
		if( length > 1 && buffer[1] == 'u') 
			if( length > 2 && buffer[2] == 'g') 
				if( length > 3 && buffer[3] == '!') {
					memcpy(stack_array, buffer, length);
                    Serial.write(stack_array[3]);}
}

void loop() {
    if (led_state == 0) {
        digitalWrite(LED_BUILTIN, HIGH);
        led_state = 1;
    } else {
        digitalWrite(LED_BUILTIN, LOW);
        led_state = 0;
    }

    Serial.write('A');
    uint32_t response_length = 0;
    serial_read_bytes((char*)&response_length, 4);
    if (response_length > FUZZ_INPUT_SIZE)
    {
        while(1){ delay(100); }
    }
    serial_read_bytes(buf, (size_t) response_length);
    process_data(buf, response_length);
}
```

**- platformio.ini file**

```
[env:disco_l4s5i_iot01a]
platform = ststm32
board = disco_l4s5i_iot01a
framework = arduino
lib_archive = no
```
